### ISSUE TITLE
Add Hyper_L

### ISSUE THREAD

**Issue by grimnight** [wez/evremap#1]
Would it be possible to add Hyper_L?
I would like to use Hyper as Mod3 in Sway.

Something like:
```
[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTHYPER"]
tap = ["KEY_ESC"]
```

**Comment by wez** [comment]
At the layer that the underlying evdev stuff works in linux, there isn't a concept of a physical hyper key.

https://unix.stackexchange.com/questions/614572/is-it-possible-to-configure-the-hyper-modifier-key-on-wayland suggests that you want to take multiple mods together in order to be recognized downstream as hyper.

So you'd probably want:

```toml
[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTCTRL", "KEY_LEFTMETA", "KEY_LEFTALT"]
tap = ["KEY_ESC"]
```
