### ISSUE TITLE
Combos also press the individual keys

### ISSUE THREAD

**Issue by cgoates** [wez/evremap#13]
Hello, your code here looks right up the alley of what I'm looking for, but I've noticed some unexpected behavior as I'm trying it out, wondering if I'm just doing something wrong.  Here's my config (minus the device name):

```
[[remap]]
input=["KEY_A", "KEY_S"]
output = ["KEY_N"]
```

Every time I hit the combo, I get not only an `n`, but also an `s` or an `a`. I was expecting/hoping to just get the `n`. Is this an expected behavior?  If so, I might take the time to dig in and see if I can resolve that at least for my own use, and I'm happy to submit a PR for it if you would like.

**Comment by wez** [comment]
I wouldn't expect it to work like that, but it wouldn't surprise me if it has been doing that all along, as my use cases always involve the main key and a modifier key, and it is typically harmless if the modifier continues to be reported.

I don't have a ton of bandwidth to investigate this, so I would value your effort to figure out what's going on and perhaps resolve it!

**Comment by and3rson** [comment]
I'm experiencing a similar issue:

```toml
[[remap]]
input = ["KEY_LEFTMETA", "KEY_I"]
output = ["KEY_UP"]
[[remap]]
input = ["KEY_LEFTMETA", "KEY_J"]
output = ["KEY_LEFT"]
[[remap]]
input = ["KEY_LEFTMETA", "KEY_K"]
output = ["KEY_DOWN"]
[[remap]]
input = ["KEY_LEFTMETA", "KEY_L"]
output = ["KEY_RIGHT"]
```

When performing the following sequence:

- press META
- press J
- press L
- release J
- release L
- release META

...the following inputs are generated by evremap:
- LEFT
- L
- RIGHT
