### ISSUE TITLE
Keyboard and mouse combo remap

### ISSUE THREAD

**Issue by Ashark** [wez/evremap#14]
There is [imwheel](https://wiki.archlinux.org/title/IMWheel) tool for X11, that allows you to remap mouse wheel events combined with keyboard modifiers. I am looking for this functionality on wayland.

The problem is that afaik, this tool (evremap) currently only allow you to map a single device, while thing that I want requires two devices.

This works (remaps mouse button):
```toml
device_name = "Logitech MX Master"

[[remap]]
input = ["BTN_RIGHT"]
output = ["KEY_PAGEUP"]
```

This also works (remaps keyboard combination):
```toml
device_name = "Logitech K850"

[[remap]]
input = ["KEY_LEFTALT", "KEY_UP"]
output = ["KEY_PAGEUP"]
```

But such thing does not work:
```toml
device_name = ["Logitech MX Master", "Logitech K850"]

[[remap]]
input = ["KEY_LEFTALT", "BTN_RIGHT"]
output = ["KEY_PAGEUP"]
```

because device_name is expected to be a string.
Can we hope such functionality will be implemented?

**Comment by Ashark** [comment]
I was [able to merge](https://unix.stackexchange.com/a/707002/264065) keyboard and mouse to a single virtual device, which allowed this remap:
```toml
device_name = "virtual merged device"

[[remap]]
input = ["KEY_LEFTALT", "BTN_RIGHT"]
output = ["KEY_PAGEUP"]
```
But the problem now seems to be in specifying a mouse wheel event instead of button in the config. Is something like this possible?
```toml
device_name = "virtual merged device"

[[remap]]
input = ["KEY_LEFTALT", "REL_WHEEL"]
output = ["KEY_LEFTCTRL", "REL_WHEEL"]
```

The utility needs to handle that REL_WHEEL somehow. It is not in `evremap list-keys` apparently.
