### ISSUE TITLE
Capslock

### ISSUE THREAD

**Issue by gdkrmr** [wez/evremap#78]
I have mapped `capslock + j` to `down` etc. and it works as intended, the problem is that it is more or less random if `capslock` gets toggled after using the key combination. Is there a way to revert `capslock` toggle to its previous state or have it always off after this?

Here is my config:

```toml
device_name = "AT Translated Set 2 keyboard"

[[remap]]
input = ["KEY_CAPSLOCK", "KEY_H"]
output = ["KEY_LEFT"]
[[remap]]
input = ["KEY_CAPSLOCK", "KEY_J"]
output = ["KEY_DOWN"]
[[remap]]
input = ["KEY_CAPSLOCK", "KEY_K"]
output = ["KEY_UP"]
[[remap]]
input = ["KEY_CAPSLOCK", "KEY_L"]
output = ["KEY_RIGHT"]
[[remap]]
input = ["KEY_CAPSLOCK", "KEY_O"]
output = ["KEY_PAGEUP"]
[[remap]]
input = ["KEY_CAPSLOCK", "KEY_U"]
output = ["KEY_PAGEDOWN"]
```
