### ISSUE TITLE
dual role keys do not work

### ISSUE THREAD

**Issue by bellissimogiorno** [wez/evremap#82]
Thank you for creating this useful tool.  There seems to be an issue with dual role keys not working as expected.

For a MWE of this issue, I set Caps Lock to produce `h` on hold and `t` on tap.  Repeatedly tapping caps five times produces the following incorrect output:

```
hththththt 
```
I would expect this output instead:
```
ttttt
```
If I press and hold, the following correct output is generated

```
h     [then autorepeat kicks in]
```
It's clear that on tap, the keypress event generates an `h`, and the key release (if [within 200ms](https://github.com/wez/evremap/blob/cc618e8b973f5c6f66682d1477b3b868a768c545/src/remapper.rs#L298), I believe) generates a `t`. I would expect it to just generate a `t`.

Here's the toml file:

```
device_name = "AT Translated Set 2 keyboard"
[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_H"]
tap = ["KEY_T"]
```

Thank you.

**Comment by pixL404** [comment]
same thing happening to me, but with my mouse

toml:
```toml
device_name = "Kensington SlimBlade Pro(2.4GHz Receiver) Kensington SlimBlade Pro Trackball(2.4GHz Receiver)"
phys = "usb-0000:13:00.4-2.2/input0"

[[dual_role]]
input = "BTN_SIDE"
hold = ["BTN_FORWARD"]
tap = ["BTN_BACK"]
```

the output when running `evremap debug-events --device-name "evremap Virtual input for /dev/input/event3"`:

```
# hold
[2024-12-31T22:31:44Z INFO  evremap] BTN_FORWARD 1
[2024-12-31T22:31:45Z INFO  evremap] BTN_FORWARD 0

# tap
[2024-12-31T22:31:51Z INFO  evremap] BTN_FORWARD 1
[2024-12-31T22:31:51Z INFO  evremap] BTN_FORWARD 0
[2024-12-31T22:31:51Z INFO  evremap] BTN_BACK 1
[2024-12-31T22:31:51Z INFO  evremap] BTN_BACK 0
```
