### ISSUE TITLE
Swap keys

### ISSUE THREAD

**Issue by tsankuanglee** [wez/evremap#9]
Wonderful utility! Could we add a function to swap keys that doesn't cause loops, i.e. swap `KEY_CAPSLOCK` and `KEY_LEFTCTRL`.

For example, I'd like the physical `CAPSLOCK` key to do the dual_role, and the physical `LEFTCTRL` to emit CAPSLOCK.
 
This doesn't work as intended:
```
[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTCTRL"]
tap = ["KEY_ESC"]

[[remap]]
input = ["KEY_LEFTCTRL"]
output = ["KEY_CAPSLOCK"]
```

I understand I can do something like:
```
[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_LEFTCTRL"]
tap = ["KEY_ESC"]

[[dual_role]]
input = "KEY_LEFTCTRL"
hold = ["KEY_LEFTCTRL"]
tap = ["KEY_CAPSLOCK"]
```
But I can still see some use case for a real swapping. Perhaps a way to specify the original "physical" key?

**Comment by ShampooDeng** [comment]
I have the problem. It seems that keys triggered via `hold` will not be prevented from matching as `input`.

So I simply make to hold key to be `KEY_RIGHTCTRL`, like this

```toml
[[dual_role]]
input = "KEY_CAPSLOCK"
hold = ["KEY_RIGHTCTRL"]
tap = ["KEY_ESC"]

[[remap]]
input = ["KEY_LEFTCTRL"]
output = ["KEY_CAPSLOCK"]
```
